# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a824c86ea86e739f6063901ed77dd5a1afbdebeb19aeb43b3dd25e0a22566c8b84e5037f8ef104df34e0a7f2182e1523e1e5c27e3bbd84b81417f13f4f8015e

test:
  secret_key_base: d8872633271a97ceadb7560822ef969513c0936f97281e52d57c7a8a9f8abff415ace686597fa6d7d1c46de93492a56c0eaa25012b1aa9a3d7355ddb2a53d8dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
